### ISSUE TITLE
prompt: nickname:  (node:17506) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency

### ISSUE THREAD

**Issue by KR1470R** [flatiron/prompt#203] opened 2020-07-01 09:02 UTC
I'm installed **prompt**, imported this in my main file js, and get this warning. How fix that?

Source of main file:
```
const prompt = require("prompt")
prompt.start()
prompt.get("nickname",function(err,res){
	if (err) return onErr(err);
	console.log("Enter your nickname: ")
	console.log(res.nickname)
})

function onErr(err) {
    console.log(err);
    return 1;
}
```

**Comment by ronbreger-cs** [comment] 2020-07-09 23:41
I have the same issue.  How can we fix this?

**Comment by KR1470R** [comment] 2020-07-10 06:37
Idk, i just used readline.

**Comment by MaffooBristol** [comment] 2020-09-28 13:23
I think this might be a dupe of https://github.com/flatiron/prompt/issues/199

**Comment by MaffooBristol** [comment] 2020-09-28 16:45
Similarly to KR1670R, I just opted to use Inquirer instead

**Comment by ezze** [comment] 2020-11-26 13:19
It should be already fixed few years ago: https://github.com/flatiron/prompt/commit/6ebf54a9be3d7332f3f8ddd51e9254277f9d4e72

But it's not published to npm registry. 1.0.0 is the latest version there published 5 years ago!

**Closed** 2020-11-26 21:00 UTC
